name = "lerf-rewards-hub"
main = "dist/index.js"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

# Database connection will be set via environment variables
# DATABASE_URL = "your_postgresql_connection_string"

[[kv_namespaces]]
binding = "CACHE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[dev]
port = 8787